### ISSUE TITLE
Loading errors

### ISSUE THREAD

**Issue by NosferatuJoe** [ManifestManah/Content-Package-Master-Collection#1]
I just installed the package including builder races and ran into 2 loading issues I thought were important enough to report:

```
[wcs/tools/manifest/corrupted_samus/load 8] repeat: The command 'repeat' could not be found
[wcs/loaders/racepack_builders/load 12] es_load: Could not open script for wcs/tools/manifest/builder_bob_the_builde
```

**Comment by ManifestManah** [comment]
`The command 'repeat' could not be found`

I believe this may be related to the Eventscripts Emulator, I am not sure that it actually does support the repeat functionality. I recall having issues with repeats in the past on CS:GO. But I will have to look in to the code to make sure the repeat itself is correctly created and used, but till I have a PC that can actually run the necessary programs to test these things out, I will have to put it on pause for the moment. 
Maybe some other people with insight in python and eventscripts can see what is going on and help come up with a solution before that :-)
